# Generated by Django 5.0.1 on 2024-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
